# Site settings
title: m0oon0
description: software path
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://m0oon0.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: m0oon0
user_description:
user_title: Software Engineer
email: moonwaterhuman@gmail.com
# twitter_username: none
# github_username:  m0oon0
# gplus_username:

exclude: ['package.json', 'src' , 'node_modules']
